<html>
<head><title></title></head>
<body>
<body style="background:url('https://mail.google.com/mail/u/0?ui=2&ik=0b207475f8&attid=0.1&permmsgid=msg-f:1689575461076340516&th=177293ee1aac0f24&view=att&disp=safe&realattid=177293e2edbde8d55501'); background-size: cover; background-repeat: no-repeat;">

<font color= white size= 5, face= Courier New > </font>
<marquee bgcolor= grey width= 1350, scrollamount= 100, scrolldelay= 700 ,behavior = "scroll" direction = right> 
<i><b>•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE• HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE•HOPE• </i></b>
</marquee>
<p align= center>
</p>
<br>
<br>
<br>
<p align= center>
<br>
<font color= grey size= 39 , face= Courier New> <b> TODAY & </b> </font>
<font color= white size= 39 , face= Courier New> <b> TOMORROW</b> </font>
<br> 
<br>
<font color= grey  size= 4 , face=  Arial> <b> "TOMORROW: A </b> </font>
<font  color= white  size= 4 , face=  Arial> <b>FUTURE WHERE </b></font> <br>
<font color= grey size= 6 , face= Century Gothic> <b>  HO</b> </font>
<font color= white size=6 face= Century Gothic> <b> PE </b> </font> <br>
 <font color= grey size= 4 , face=  Arial> <b>TAKES AWAY </b></font>
<font  color= white  size= 4 , face=  Arial> <b>THE SUFFERING" </b> </font>
<br>
<br>
<img src= "C:\Users\ACER\Downloads\week3 - Copy/covid.jpg" width = "500", length = "400"> </img> 
<br>
<br>
<br>
<font color= yellow , size= 15 , face= Courier New> <b> "TODAY LET'S MAKE A DIFFERENCE" </b>
</p>
<p align= right>
<font color= black , size= 3 , face= Arial> <b> ©️CMDAS </b>
</body>
</html>
